import { MenuItem, Order, User, Category } from './index';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'All', icon: '🍽️', count: 25 },
  { id: '2', name: 'Meals', icon: '🍽️', count: 8 },
  { id: '3', name: 'Snacks', icon: '🥪', count: 6 },
  { id: '4', name: 'Beverages', icon: '☕', count: 5 },
  { id: '5', name: 'Desserts', icon: '🍰', count: 3 },
  { id: '6', name: 'Breakfast', icon: '🥐', count: 2 },
  { id: '7', name: 'Specials', icon: '⭐', count: 1 },
];

export const MENU_ITEMS: MenuItem[] = [
  // Meals
  {
    id: 'm1',
    name: 'Paneer Tikka Biryani',
    description: 'Fragrant basmati rice layered with tender paneer tikka, aromatic spices, and fresh herbs',
    price: 220,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a104?w=400&h=300&fit=crop',
    category: 'Meals',
    rating: 4.8,
    reviews: 342,
    isVeg: true,
    isTrending: true,
    isSpecial: false,
    prepTime: 12,
    calories: 450,
    tags: ['veg', 'trending', 'spicy'],
  },
  {
    id: 'm2',
    name: 'Butter Chicken',
    description: 'Creamy tomato-based curry with tender chicken pieces, served with basmati rice and naan',
    price: 280,
    image: 'https://images.unsplash.com/photo-1603872670686-9f45de5d4bf7?w=400&h=300&fit=crop',
    category: 'Meals',
    rating: 4.9,
    reviews: 521,
    isVeg: false,
    isTrending: true,
    isSpecial: false,
    prepTime: 15,
    calories: 520,
    tags: ['non-veg', 'trending', 'creamy'],
  },
  {
    id: 'm3',
    name: 'Chole Bhature',
    description: 'Fluffy deep-fried bread paired with spiced chickpea curry, onions, and chutney',
    price: 150,
    image: 'https://images.unsplash.com/photo-1605034637607-dc2c3d47f5c8?w=400&h=300&fit=crop',
    category: 'Meals',
    rating: 4.6,
    reviews: 289,
    isVeg: true,
    isTrending: true,
    isSpecial: false,
    prepTime: 10,
    calories: 380,
    tags: ['veg', 'trending', 'spicy'],
  },
  {
    id: 'm4',
    name: 'Tandoori Chicken',
    description: 'Succulent chicken marinated in yogurt and spices, grilled to perfection',
    price: 250,
    image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd64fdf?w=400&h=300&fit=crop',
    category: 'Meals',
    rating: 4.7,
    reviews: 418,
    isVeg: false,
    isTrending: true,
    isSpecial: true,
    prepTime: 14,
    calories: 380,
    tags: ['non-veg', 'trending', 'special'],
  },
  {
    id: 'm5',
    name: 'Paneer Makhani Pasta',
    description: 'Creamy makhani sauce with tender paneer cubes mixed with al dente pasta',
    price: 200,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop',
    category: 'Meals',
    rating: 4.5,
    reviews: 156,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 11,
    calories: 420,
    tags: ['veg', 'italian', 'creamy'],
  },
  {
    id: 'm6',
    name: 'Fish Curry',
    description: 'Tender fish cooked in aromatic coconut curry with traditional spices',
    price: 290,
    image: 'https://images.unsplash.com/photo-1612874742237-6526221fcf4f?w=400&h=300&fit=crop',
    category: 'Meals',
    rating: 4.7,
    reviews: 267,
    isVeg: false,
    isTrending: false,
    isSpecial: false,
    prepTime: 13,
    calories: 380,
    tags: ['non-veg', 'seafood', 'spicy'],
  },
  {
    id: 'm7',
    name: 'Veggie Burger',
    description: 'Homemade veggie patty with fresh lettuce, tomato, and special mayo sauce',
    price: 140,
    image: 'https://images.unsplash.com/photo-1585238341710-4b4971ff63d5?w=400&h=300&fit=crop',
    category: 'Meals',
    rating: 4.4,
    reviews: 198,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 8,
    calories: 320,
    tags: ['veg', 'fast', 'american'],
  },
  {
    id: 'm8',
    name: 'Chicken Fried Rice',
    description: 'Fluffy rice wok-tossed with tender chicken, veggies, and aromatic spices',
    price: 180,
    image: 'https://images.unsplash.com/photo-1603271867882-5c9fd74d3e67?w=400&h=300&fit=crop',
    category: 'Meals',
    rating: 4.6,
    reviews: 334,
    isVeg: false,
    isTrending: true,
    isSpecial: false,
    prepTime: 10,
    calories: 420,
    tags: ['non-veg', 'trending', 'asian'],
  },

  // Snacks
  {
    id: 's1',
    name: 'Samosa',
    description: 'Crispy golden-fried triangle pastry filled with spiced potato and peas',
    price: 30,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop',
    category: 'Snacks',
    rating: 4.5,
    reviews: 892,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 5,
    calories: 150,
    tags: ['veg', 'fried', 'snack'],
  },
  {
    id: 's2',
    name: 'Spring Rolls',
    description: 'Crispy rolls filled with vegetables and served with sweet and spicy sauce',
    price: 80,
    image: 'https://images.unsplash.com/photo-1554520595-f3caf78d62d6?w=400&h=300&fit=crop',
    category: 'Snacks',
    rating: 4.6,
    reviews: 421,
    isVeg: true,
    isTrending: true,
    isSpecial: false,
    prepTime: 7,
    calories: 200,
    tags: ['veg', 'trending', 'asian'],
  },
  {
    id: 's3',
    name: 'Onion Pakora',
    description: 'Crispy onion fritters deep-fried in chickpea flour batter',
    price: 50,
    image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd64fdf?w=400&h=300&fit=crop',
    category: 'Snacks',
    rating: 4.4,
    reviews: 567,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 6,
    calories: 180,
    tags: ['veg', 'fried', 'snack'],
  },
  {
    id: 's4',
    name: 'Chicken Wings',
    description: 'Spicy marinated chicken wings tossed in tangy sauce',
    price: 120,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=300&fit=crop',
    category: 'Snacks',
    rating: 4.7,
    reviews: 678,
    isVeg: false,
    isTrending: true,
    isSpecial: false,
    prepTime: 9,
    calories: 320,
    tags: ['non-veg', 'trending', 'spicy'],
  },
  {
    id: 's5',
    name: 'Veggie Fries',
    description: 'Crispy seasoned vegetable fries with herb mayo and ketchup',
    price: 70,
    image: 'https://images.unsplash.com/photo-1584622614875-2f3256e7f426?w=400&h=300&fit=crop',
    category: 'Snacks',
    rating: 4.3,
    reviews: 445,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 5,
    calories: 220,
    tags: ['veg', 'fried', 'fast'],
  },
  {
    id: 's6',
    name: 'Cheese Garlic Bread',
    description: 'Toasted bread with melted cheese and roasted garlic butter',
    price: 90,
    image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd64fdf?w=400&h=300&fit=crop',
    category: 'Snacks',
    rating: 4.5,
    reviews: 356,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 6,
    calories: 280,
    tags: ['veg', 'bread', 'cheesy'],
  },

  // Beverages
  {
    id: 'b1',
    name: 'Iced Latte',
    description: 'Smooth espresso with cold milk and ice, topped with foam',
    price: 80,
    image: 'https://images.unsplash.com/photo-1577968345615-db4ee3db7d64?w=400&h=300&fit=crop',
    category: 'Beverages',
    rating: 4.6,
    reviews: 523,
    isVeg: true,
    isTrending: true,
    isSpecial: false,
    prepTime: 4,
    calories: 120,
    tags: ['coffee', 'cold', 'trending'],
  },
  {
    id: 'b2',
    name: 'Fresh Mango Smoothie',
    description: 'Creamy smoothie made from fresh mango puree and yogurt',
    price: 100,
    image: 'https://images.unsplash.com/photo-1590080876003-b4ee3f1b6b1f?w=400&h=300&fit=crop',
    category: 'Beverages',
    rating: 4.7,
    reviews: 612,
    isVeg: true,
    isTrending: true,
    isSpecial: true,
    prepTime: 5,
    calories: 240,
    tags: ['smoothie', 'fruit', 'special'],
  },
  {
    id: 'b3',
    name: 'Masala Chai',
    description: 'Aromatic Indian tea with spices, ginger, and milk',
    price: 40,
    image: 'https://images.unsplash.com/photo-1597318204467-e37e91196c3c?w=400&h=300&fit=crop',
    category: 'Beverages',
    rating: 4.5,
    reviews: 734,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 5,
    calories: 80,
    tags: ['tea', 'hot', 'indian'],
  },
  {
    id: 'b4',
    name: 'Virgin Mojito',
    description: 'Refreshing mint and lime cooler with sparkling water',
    price: 90,
    image: 'https://images.unsplash.com/photo-1582895106404-8f1618153142?w=400&h=300&fit=crop',
    category: 'Beverages',
    rating: 4.6,
    reviews: 445,
    isVeg: true,
    isTrending: true,
    isSpecial: false,
    prepTime: 6,
    calories: 100,
    tags: ['mocktail', 'cold', 'trending'],
  },
  {
    id: 'b5',
    name: 'Banana Chocolate Shake',
    description: 'Rich chocolate shake blended with fresh banana and milk',
    price: 110,
    image: 'https://images.unsplash.com/photo-1578914848667-b8a4fc1908f1?w=400&h=300&fit=crop',
    category: 'Beverages',
    rating: 4.8,
    reviews: 589,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 5,
    calories: 320,
    tags: ['shake', 'chocolate', 'creamy'],
  },

  // Desserts
  {
    id: 'd1',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a molten center, served with vanilla ice cream',
    price: 150,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
    category: 'Desserts',
    rating: 4.9,
    reviews: 823,
    isVeg: true,
    isTrending: true,
    isSpecial: false,
    prepTime: 8,
    calories: 420,
    tags: ['dessert', 'chocolate', 'trending'],
  },
  {
    id: 'd2',
    name: 'Gulab Jamun',
    description: 'Soft milk dumplings in warm sugar syrup with cardamom and rose essence',
    price: 80,
    image: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd64fdf?w=400&h=300&fit=crop',
    category: 'Desserts',
    rating: 4.7,
    reviews: 456,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 6,
    calories: 200,
    tags: ['dessert', 'indian', 'sweet'],
  },
  {
    id: 'd3',
    name: 'Cheesecake Slice',
    description: 'Creamy New York style cheesecake with graham cracker base',
    price: 130,
    image: 'https://images.unsplash.com/photo-1577934212617-8d1d2c80d41f?w=400&h=300&fit=crop',
    category: 'Desserts',
    rating: 4.8,
    reviews: 534,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 5,
    calories: 380,
    tags: ['dessert', 'cake', 'creamy'],
  },

  // Breakfast
  {
    id: 'br1',
    name: 'Masala Dosa',
    description: 'Crispy rice and lentil crepe filled with spiced potato, served with chutney',
    price: 120,
    image: 'https://images.unsplash.com/photo-1605034637607-dc2c3d47f5c8?w=400&h=300&fit=crop',
    category: 'Breakfast',
    rating: 4.7,
    reviews: 612,
    isVeg: true,
    isTrending: true,
    isSpecial: false,
    prepTime: 10,
    calories: 280,
    tags: ['breakfast', 'veg', 'trending'],
  },
  {
    id: 'br2',
    name: 'Scrambled Eggs on Toast',
    description: 'Fluffy scrambled eggs on buttered toast with fresh herbs and tomato',
    price: 100,
    image: 'https://images.unsplash.com/photo-1533134242443-742f0a64ee11?w=400&h=300&fit=crop',
    category: 'Breakfast',
    rating: 4.5,
    reviews: 378,
    isVeg: true,
    isTrending: false,
    isSpecial: false,
    prepTime: 7,
    calories: 320,
    tags: ['breakfast', 'eggs', 'simple'],
  },

  // Special
  {
    id: 'sp1',
    name: 'Chef\'s Special Thali',
    description: 'Complete meal with paneer curry, dal, rice, bread, pickle, and dessert',
    price: 320,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop',
    category: 'Specials',
    rating: 4.9,
    reviews: 945,
    isVeg: true,
    isTrending: true,
    isSpecial: true,
    prepTime: 18,
    calories: 650,
    tags: ['special', 'thali', 'veg', 'complete'],
  },
];

export const MOCK_USER: User = {
  id: 'user1',
  name: 'Rahul Kumar',
  email: 'rahul@college.edu',
  avatar: 'https://i.pravatar.cc/150?img=12',
  walletBalance: 247.5,
  loyaltyPoints: 1240,
  loyaltyTier: 'silver',
  ordersCount: 24,
  createdAt: new Date('2024-01-15'),
};

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD001',
    userId: 'user1',
    items: [
      {
        menuItem: MENU_ITEMS[0],
        quantity: 1,
        price: 220,
      },
      {
        menuItem: MENU_ITEMS[9],
        quantity: 2,
        price: 160,
      },
    ],
    status: 'preparing',
    totalAmount: 421,
    queuePosition: 3,
    estimatedTime: 8,
    createdAt: new Date(Date.now() - 5 * 60000),
  },
  {
    id: 'ORD002',
    userId: 'user1',
    items: [
      {
        menuItem: MENU_ITEMS[2],
        quantity: 1,
        price: 150,
      },
    ],
    status: 'ready',
    totalAmount: 150,
    queuePosition: 1,
    estimatedTime: 0,
    createdAt: new Date(Date.now() - 25 * 60000),
    qrCode: 'ORD002QR',
  },
  {
    id: 'ORD003',
    userId: 'user1',
    items: [
      {
        menuItem: MENU_ITEMS[1],
        quantity: 1,
        price: 280,
      },
    ],
    status: 'picked',
    totalAmount: 280,
    queuePosition: 0,
    estimatedTime: 0,
    createdAt: new Date(Date.now() - 2 * 60 * 60000),
    pickupTime: new Date(Date.now() - 95 * 60000),
  },
  {
    id: 'ORD004',
    userId: 'user1',
    items: [
      {
        menuItem: MENU_ITEMS[19],
        quantity: 1,
        price: 120,
      },
    ],
    status: 'picked',
    totalAmount: 120,
    queuePosition: 0,
    estimatedTime: 0,
    createdAt: new Date(Date.now() - 24 * 60 * 60000),
    pickupTime: new Date(Date.now() - 24 * 60 * 60000 + 10 * 60000),
  },
  {
    id: 'ORD005',
    userId: 'user1',
    items: [
      {
        menuItem: MENU_ITEMS[4],
        quantity: 1,
        price: 200,
      },
      {
        menuItem: MENU_ITEMS[12],
        quantity: 1,
        price: 100,
      },
    ],
    status: 'placed',
    totalAmount: 330,
    queuePosition: 12,
    estimatedTime: 18,
    createdAt: new Date(Date.now() - 1 * 60000),
  },
];
